import { black, grayDark, grayShadow, primary, white } from 'config/colors';
import {
  StyleSheet
} from 'react-native';

export const styles = StyleSheet.create({
  divider: {
      position: 'relative',
      marginTop: 5,
      marginBottom: 20,
      borderBottomColor: grayDark,
      borderBottomWidth: 1,
      alignSelf: 'center',
      width: '80%',
  },
  titleText: {
    fontSize: 32,
    fontWeight: '600',
    color: white,
    top: 80,
  },
  sectionText: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 20,
    paddingLeft: 40,
  },
  bodyText: {
    fontSize: 14,
    fontWeight: '200',
    color: black,
    marginBottom: 15,
    fontFamily: 'Helvetica',
    paddingLeft: 45,
    paddingRight: 45,
  },
  imageHeader: {
    width: '100%',
    height: 160,
    zIndex: -10,
  },
  backIcon: {
    backgroundColor: primary,
    borderRadius: 10,
    borderColor: white,
    borderWidth: 1,
    position: 'absolute',
    left: 20,
    top: 40,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continue: {
    position: 'absolute',
    bottom: -80,
    left: 20,
    right: 20,
    backgroundColor: primary,
    height: 50,
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: grayShadow,
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 3,
  },
  input: {
      borderColor: grayDark,
      borderWidth: 1,
      borderRadius: 5,
      width: 35,
      textAlign: 'center',
      paddingHorizontal: 5,
      marginHorizontal: 5,
  },
  removeButton: {
    borderColor: primary,
    borderWidth: 1,
    paddingHorizontal: 2,
    borderRadius: 5,
    paddingVertical: 1,
    marginLeft: 5,
    backgroundColor: primary,
  },
  removeButtonGray: {
    borderColor: grayDark,
    borderWidth: 1,
    paddingHorizontal: 2,
    borderRadius: 5,
    paddingVertical: 1,
    marginLeft: 5,
  },
  addButton: {
    borderColor: primary,
    borderWidth: 1,
    paddingHorizontal: 2,
    borderRadius: 5,
    backgroundColor: primary,
  },
  addButtonGray: {
    borderColor: grayDark,
    borderWidth: 1,
    paddingHorizontal: 2,
    borderRadius: 5,
  },
  buttonText: {
      fontSize: 16,
  },
  inputIntro: {
    alignSelf: 'center',
    height: 140,
    width: '75%',
    borderWidth: 1,
    borderColor: grayDark,
    borderRadius: 7,
    paddingLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    paddingBottom: 50,
    paddingTop: 10,
  },
  tourNameBox: {
    alignSelf: 'center',
    height: 35,
    width: '80%',
    borderWidth: 1,
    borderColor: grayDark,
    borderRadius: 7,
    paddingLeft: 10,
    marginTop: 10,
    marginBottom: 30,
    paddingVertical: 10,
  },
});